spring.application.name=MtsRoutingProject
spring.application.database-count=3

spring.datasource.primary.url=${SPRING_DATASOURCE_PRIMARY_URL:jdbc:postgresql://localhost:5432/db_primary}
spring.datasource.secondary.url=${SPRING_DATASOURCE_SECONDARY_URL:jdbc:postgresql://localhost:5433/db_secondary}
spring.datasource.tertiary.url=${SPRING_DATASOURCE_TERTIARY_URL:jdbc:postgresql://localhost:5434/db_tertiary}

spring.datasource.primary.username=${SPRING_DATASOURCE_PRIMARY_USERNAME:postgres}
spring.datasource.primary.password=${SPRING_DATASOURCE_PRIMARY_PASSWORD:postgres}

spring.datasource.secondary.username=${SPRING_DATASOURCE_SECONDARY_USERNAME:postgres}
spring.datasource.secondary.password=${SPRING_DATASOURCE_SECONDARY_PASSWORD:postgres}

spring.datasource.tertiary.username=${SPRING_DATASOURCE_TERTIARY_USERNAME:postgres}
spring.datasource.tertiary.password=${SPRING_DATASOURCE_TERTIARY_PASSWORD:postgres}

spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

logging.level.org.flywaydb=DEBUG
